steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fashion-scraper:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fashion-scraper:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'fashion-scraper'
    - '--image'
    - 'gcr.io/$PROJECT_ID/fashion-scraper:latest'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--memory'
    - '4Gi'
    - '--cpu'
    - '2'
    - '--timeout'
    - '3600'
    - '--max-instances'
    - '1'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/fashion-scraper:latest'
